### ISSUE TITLE
Interface is visually broken in 10.13

### ISSUE THREAD

**Issue by jotkailay** [jenghis/airbass#2]
This is only a cosmetic issue. The controller is visually "broken" with the latest macOS High Sierra. This happens in both minimal mode and cover art mode. I have a attached a pictures.

Thank you for this awesome application.

<img width="338" alt="screen shot 2018-05-30 at 11 38 49 pm" src="https://user-images.githubusercontent.com/929580/40765888-c1efb484-6462-11e8-9e15-ee698e7f8a15.png">

**Comment by pabloheimplatz** [comment]
Same for me in 10.14 and unfortunately not usable any longer because it crashes if you try to play music.

**Comment by jotkailay** [comment]
It still works great for me, crashes maybe twice a week but that is fine. Its just the interface that is broken. I downloaded the source to see if I could contribute and fix the issue but with AirTunes I get stuff on the Common Crypto part
